version: '3.7'

services:
  mysql:
    build:
      context: ./
      dockerfile: docker/db/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    networks:
      - backend

  express-server:
    build:
      context: ./
      target: ${NODE_ENV}-build-stage
      dockerfile: docker/server/Dockerfile
    container_name: express-server
    ports:
      - ${PORT}:${PORT}
      - '9229:9229'
    volumes:
      # https://burnedikt.com/dockerized-node-development-and-mounting-node-volumes/#improving-the-workaround
      # https://github.com/BretFisher/node-docker-good-defaults
      - ./:/usr/local/app/
        # the volume above prevents our host system's node_modules to be mounted
      - exclude:/usr/local/app/node_modules/
    restart: 'unless-stopped'
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  exclude:
  mysql_data:
    driver: local
